name: "Podcast Generator"
author: "Ihor Riabenko"
description: "Generates a feed for a podcast from a YAML file"
runs:
 using: "docker"
 image: "Dockerfile"
branding:
 icon: "git-branch"
 color: "red"
inputs:
  email:
    description: "The commiter's email adres"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    
